version: "3.6"

services:
  app:
    image: splunk/splunk:9.0
    platform: linux/amd64
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}/.:/opt/splunk/etc/apps/React-App
      - ${LOCAL_WORKSPACE_FOLDER:-./}/splunk-default.yml:/tmp/defaults/default.yml
    environment:
      SPLUNK_PASSWORD: splunkdev
      SPLUNK_START_ARGS: "--accept-license"
    ports:
      - 8000:8000
